# Generated by Django 5.1.1 on 2024-10-08 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_adress_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'permissions': [('send_private_email', 'Can send private email to user by the button')]},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='category',
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'product')},
        ),
    ]
