# Generated by Django 5.1.1 on 2024-10-08 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_customer_email_customer_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
